### ISSUE TITLE
Capture all unknown errors in backend to send to the log

### ISSUE THREAD

**Issue by joulev** [joulev/ezkomment#100]
This is how the frontend error boundary currently logs all uncaught/unknown errors:

https://github.com/joulev/ezkomment/blob/7733127c737a04beda6faace5961a42aaaef69a5/client/layouts/errors.tsx#L55-L69

The `/api/error` route is there and you can use it to log all uncaught errors on the backend too. The Vercel deployment already has all necessary environment variables.

I will check the log once every day (or every two days) and will notify if any anomalies occur.

**Comment by VietAnh1010** [comment]
I will delete the `/api/error` endpoint, it should be converted to a utility.
`next-connect`'s configurations have an `onError` property, I will use that to log the uncaught errors.

**Comment by joulev** [comment]
No, `/api/error` is used to send a request to the Axiom dataset. I do not want to expose that Axiom URL and API key to the client side, so an API route is necessary. It’s called [URL masking](https://nextjs.org/docs/api-routes/introduction#use-cases).

Instead you may change it to a function, then call that function inside `/api/error` and your `onError`.

**Comment by VietAnh1010** [comment]
> No, /api/error is used to send a request to the Axiom dataset. I do not want to expose that Axiom URL and API key to the client-side, so an API route is necessary. It’s called [URL masking](https://nextjs.org/docs/api-routes/introduction#use-cases).

Hmm, similar to Proxy? Okay, I will keep the endpoint.

**Comment by joulev** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/44609036/173777376-c98957e6-6519-4bb8-9b3d-37b7ef7d85b9.png">

Errors so far.

Might be a good idea to (1) only send errors to the log in production mode and (2) log more details (to identify the source of the error, where it went wrong, etc. easier).

**Comment by VietAnh1010** [comment]
> (1) only send errors to the log in production mode and (2) log more details (to identify the source of the error, where it went wrong, etc. easier).

I have changed the code so that it only send errors to the log in production mode &ndash; it is not very hard. For (2) I will send the errors' stack trace together with their message as well.

Some specific errors will be catched and handled appropriately, for example: if a user or record is not found then the error will be catched and `404` status code will be sent back. Other errors will not be catched and will be logged.

But Firebase lacks documentation for the errors that could happen when dealing with Firestore and Firebase Storage. And I cannot access Firebase errors' types information &ndash; making the implementation much harder.

And why the hell does JS/TS allow anything to be thrown instead of only allowing `Error` and its subclass to be thrown?
