### ISSUE TITLE
Implement notification feature

### ISSUE THREAD

**Issue by VietAnh1010** [joulev/ezkomment#225]
I create a separate issue to keep track of the progress of this feature.

A few things to note at the moment:

- [x] Create a new endpoint such that when a new user is registered into the app, the front end should send a request to this endpoint. A welcome notification will be generated and sent back to the client.
- [x] Create another endpoint to get all notifications.
- [x] A mechanism to delete one and all notification(s)

**Comment by joulev** [comment]
I think notifications should be integrated to the user object. Why? The notification is needed any time the user is logged in (the notification icon is visible from everywhere in the app). So instead of having a separate endpoint, integrate it to `GET /users/:uid`.

I would then be able to `POST` to that route to generate the welcome notification, since otherwise there’s no way the frontend knows whether a newly-authenticated user is a new account or not.

Something like `if user.notifications.length == 0 then POST`.

Or should this be done in the backend automatically? Like in the `GET /users/:uid` if you find the `notifications` array to be empty, you add the welcome automatically.

**Comment by VietAnh1010** [comment]
Hmm, I don't really like this design.

The problem is that `GET /users/:uid/` does too much, which may slow the application down considerably.

Notification should be separated, we can load it in the background. Similar to Facebook, I guess.

Another question is whether should we retain read notifications. I don't think that is a good design, as now whenever we GET all the notifications we receive a lot of unnecessary data, which again, hurts performance.

Deleting the notification after it is read is much more reasonable. And if I design the notification feature this way, then:

> Something like if user.notifications.length == 0 then POST.

will not work.

**Comment by joulev** [comment]
> Also, an endpoint like this can be reused in the future if we add more features to the app. After a new user is registered into the app, just send a single request to this endpoint, let's call it /users/:uid/initialize. All logics related to initializing a new user will be handled in a single request.

Agreed, this is the best way out of this. Then add a `initialised: boolean` field to the user object, so when he logs in I can check `if !initialised then POST` so as not to spam the server every time he authenticates.

I mean I *could have* checked `if !emailVerified` or `if user.metadata.creationTime < now() - 1 minute`, but that would be too hacky.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/44609036/181674536-105c1768-4504-4dab-a92e-4e07b4663890.png">

**Comment by joulev** [comment]
Oh never mind, you don't even need to add that field. Client SDK already has [`AdditionalUserInfo.isNewUser`](https://firebase.google.com/docs/reference/js/auth.additionaluserinfo.md#additionaluserinfoisnewuser).
